name: Backend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'web/TripMate_Webapi/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'web/TripMate_Webapi/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: web/TripMate_Webapi/TripMate_Webapi

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -o publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: web/TripMate_Webapi/TripMate_Webapi/publish
